name: Schedule Test

on:
  push:

  schedule:
    - cron: "3-59/5 * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test trigger
        run: |
          echo "================================"
          echo "TRIGGER TEST"
          echo "================================"
          date -u
          echo "event=${{ github.event_name }}"
          echo "repository=${{ github.repository }}"
